<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Close</name>
   <tag></tag>
   <elementGuidId>fee557cf-55cb-4539-a22c-2c9377ddd8be</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//button[@type = 'button' and (text() = 'Close' or . = 'Close')]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>95167ef7-21a3-4071-82d3-09a2ff794ecd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>b76e0e39-5c29-48e9-b22c-904358a30e36</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>focus:tw-ring-ring data-[state=open]:tw-bg-accent data-[state=open]:tw-text-muted-foreground tw-absolute tw-end-4 tw-top-4 tw-z-10 tw-m-auto tw-flex tw-h-[35px] tw-h-[45px] tw-w-[35px] tw-w-[45px] tw-cursor-pointer tw-items-center tw-justify-center tw-rounded-full tw-bg-white tw-leading-none tw-shadow tw-transition tw-duration-150 tw-ease-in-out hover:tw-bg-[#efefef] focus:tw-outline-none focus:tw-ring-2 focus:tw-ring-offset-2 disabled:tw-pointer-events-none</value>
      <webElementGuid>8884a872-d1cf-437a-9131-c35d5e141383</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Close</value>
      <webElementGuid>fe60e26a-e7c9-4dec-bfe8-a47ccbea3fee</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;radix-:r1a:&quot;)/button[@class=&quot;focus:tw-ring-ring data-[state=open]:tw-bg-accent data-[state=open]:tw-text-muted-foreground tw-absolute tw-end-4 tw-top-4 tw-z-10 tw-m-auto tw-flex tw-h-[35px] tw-h-[45px] tw-w-[35px] tw-w-[45px] tw-cursor-pointer tw-items-center tw-justify-center tw-rounded-full tw-bg-white tw-leading-none tw-shadow tw-transition tw-duration-150 tw-ease-in-out hover:tw-bg-[#efefef] focus:tw-outline-none focus:tw-ring-2 focus:tw-ring-offset-2 disabled:tw-pointer-events-none&quot;]</value>
      <webElementGuid>5fafd146-8100-4af3-a6a1-a486c03d4abf</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>(//button[@type='button'])[8]</value>
      <webElementGuid>8dedcd7f-5dfb-436b-bccd-b485146ded5e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='radix-:r1a:']/button</value>
      <webElementGuid>cc4249ef-33da-4292-94ae-3465bd7e00c4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='احصل على العروض'])[1]/following::button[1]</value>
      <webElementGuid>f3b24edb-415d-4785-9d47-ad8318399cb3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='بدأت مفاجآتنا الآن!'])[1]/following::button[2]</value>
      <webElementGuid>7af610e4-7d8b-4d8e-b3d6-76aed0a23dd1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/button</value>
      <webElementGuid>ce06ace4-c7df-423d-b198-f4fe3ff594ad</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@type = 'button' and (text() = 'Close' or . = 'Close')]</value>
      <webElementGuid>4c359179-173d-4edd-a49f-9a8fe5431695</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
