<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_for_seccuss_download</name>
   <tag></tag>
   <elementGuidId>c1a9719e-67f8-4f1d-b2b8-54774de74cf1</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//li[(text() = 'تم التحميل بنجاح' or . = 'تم التحميل بنجاح')]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>li</value>
      <webElementGuid>3fd76c8c-b958-4eb2-94b7-8230ffc97f0c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>status</value>
      <webElementGuid>a60679af-1082-419c-9d7e-27d1d17493f1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-live</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>dbf26c89-234e-4bbe-9437-39194decaab9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-atomic</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>12db8277-6415-4e21-ad71-415d2b4ec2bc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>195e2c5a-4779-46ad-967e-ed064fc4342a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-state</name>
      <type>Main</type>
      <value>open</value>
      <webElementGuid>b5f3c704-9d5e-4bf2-9775-0e8d25f36351</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-swipe-direction</name>
      <type>Main</type>
      <value>right</value>
      <webElementGuid>8b419d64-43d1-4757-b8e6-404279366483</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>tw-group tw-pointer-events-auto tw-relative tw-flex tw-w-full tw-items-center tw-justify-between tw-space-x-4 tw-overflow-hidden tw-rounded-md tw-border tw-border-slate-200 tw-p-6 tw-pr-8 tw-shadow-lg tw-transition-all data-[swipe=cancel]:tw-translate-x-0 data-[swipe=end]:tw-translate-x-[var(--radix-toast-swipe-end-x)] data-[swipe=move]:tw-translate-x-[var(--radix-toast-swipe-move-x)] data-[swipe=move]:tw-transition-none data-[state=open]:tw-animate-in data-[state=closed]:tw-animate-out data-[swipe=end]:tw-animate-out data-[state=closed]:tw-fade-out-80 data-[state=closed]:tw-slide-out-to-right-full data-[state=open]:tw-slide-in-from-top-full data-[state=open]:sm:tw-slide-in-from-bottom-full dark:tw-border-slate-800 tw-destructive tw-group tw-border-[#00CE7C] tw-bg-[#00CE7C] tw-text-slate-50 dark:tw-border-[#00CE7C] dark:tw-bg-[#00CE7C] dark:tw-text-slate-50</value>
      <webElementGuid>be1cbee3-47d2-4450-bd7f-59a81b1f7561</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>dir</name>
      <type>Main</type>
      <value>rtl</value>
      <webElementGuid>891bc925-338c-4368-b157-cbac58df657d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-swipe</name>
      <type>Main</type>
      <value>cancel</value>
      <webElementGuid>9012ae72-15d0-425e-89dc-f2f0e7e2ccc5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>تم التحميل بنجاح</value>
      <webElementGuid>066583f1-576d-4394-9b92-b217bdb9ec0e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;__next&quot;)/div[2]/ol[@class=&quot;tw-fixed tw-top-0 tw-z-[35000000] tw-flex tw-max-h-screen tw-w-full tw-flex-col-reverse tw-p-4 sm:tw-bottom-0 sm:tw-right-0 sm:tw-top-auto sm:tw-flex-col md:tw-max-w-[420px]&quot;]/li[@class=&quot;tw-group tw-pointer-events-auto tw-relative tw-flex tw-w-full tw-items-center tw-justify-between tw-space-x-4 tw-overflow-hidden tw-rounded-md tw-border tw-border-slate-200 tw-p-6 tw-pr-8 tw-shadow-lg tw-transition-all data-[swipe=cancel]:tw-translate-x-0 data-[swipe=end]:tw-translate-x-[var(--radix-toast-swipe-end-x)] data-[swipe=move]:tw-translate-x-[var(--radix-toast-swipe-move-x)] data-[swipe=move]:tw-transition-none data-[state=open]:tw-animate-in data-[state=closed]:tw-animate-out data-[swipe=end]:tw-animate-out data-[state=closed]:tw-fade-out-80 data-[state=closed]:tw-slide-out-to-right-full data-[state=open]:tw-slide-in-from-top-full data-[state=open]:sm:tw-slide-in-from-bottom-full dark:tw-border-slate-800 tw-destructive tw-group tw-border-[#00CE7C] tw-bg-[#00CE7C] tw-text-slate-50 dark:tw-border-[#00CE7C] dark:tw-bg-[#00CE7C] dark:tw-text-slate-50&quot;]</value>
      <webElementGuid>83f76f3a-b651-4738-9036-7950c322b50f</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='__next']/div[2]/ol/li</value>
      <webElementGuid>9f4e9176-f111-44f6-827e-fa177c5402b9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='صفحاتنا على مواقع التواصل الاجتماعي'])[1]/following::li[1]</value>
      <webElementGuid>54f465ea-b0c3-4aba-88f8-ef8c523fa3d7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='WINDOWS'])[1]/following::li[1]</value>
      <webElementGuid>8e4eb65c-df75-4128-8bce-eb65f00fc45b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li</value>
      <webElementGuid>5320d659-547d-4075-ae67-463c553316b5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//li[(text() = 'تم التحميل بنجاح' or . = 'تم التحميل بنجاح')]</value>
      <webElementGuid>06edad64-d4bd-4c34-9f1a-e96f9c8b0b70</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
