<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_for_detail_thecoursse</name>
   <tag></tag>
   <elementGuidId>6e2a3fab-03ea-49df-825f-8c1fd17521df</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>(//a[contains(text(),'تفاصيل الدورة')])[7]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>27b5c1f1-d02d-4657-a3a7-a4f6e638ea23</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>tw-max-w-full tw-w-full tw-transition tw-ease-in-out tw-duration-150 tw-font-bold tw-flex tw-items-center tw-justify-center tw-transition tw-ease-in-out tw-duration-150 styles_buttonVariantOutline__gf_i8 styles_buttonColorBlue__0VHnR tw-rounded-[10px] tw-cursor-pointer tw-text-[14px] tw-py-[5px] tw-px-[10px] !tw-text-center</value>
      <webElementGuid>d206c9c2-560c-44dc-9538-71da02d298ec</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>target</name>
      <type>Main</type>
      <value>_self</value>
      <webElementGuid>71a76784-d493-43c1-af51-a4f64d84dbeb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>/courses/%D8%A7%D9%84%D8%B9%D9%84%D9%88%D9%85-%D8%A7%D9%84%D8%B5%D9%81-%D8%A7%D9%84%D8%B1%D8%A7%D8%A8%D8%B9-%D9%81%D8%B5%D9%84-%D8%A7%D9%88%D9%84-%D8%B1%D8%BA%D8%AF-%D9%81%D8%B1%D8%AD%D8%A7%D9%86%D8%A9</value>
      <webElementGuid>9fae126c-7e1e-4a3f-bd1c-18025e1cbf6c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>تفاصيل الدورة</value>
      <webElementGuid>17bfca1d-d3de-4914-960a-393d13f778f9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;__next&quot;)/div[@class=&quot;tw-flex tw-min-h-screen tw-w-full tw-flex-col tw-justify-between tw-bg-gradient-to-br tw-from-[#905DF5] tw-to-[#813BEC]&quot;]/div[@class=&quot;tw-w-full&quot;]/div[@class=&quot;tw-relative tw-flex tw-w-full&quot;]/div[@class=&quot;tw-flex tw-flex-col tw-relative !tw-w-full tw-px-4 md:tw-px-[30px] lg:tw-px-[40px] 2xl:tw-px-[100px] tw-w-full !tw-overflow-hidden&quot;]/div[1]/section[@class=&quot;tw-my-5 tw-space-y-8 tw-px-2 md:tw-px-10&quot;]/div[@class=&quot;tw-rounded-lg tw-border tw-border-slate-200 tw-bg-white tw-text-slate-950 tw-shadow-sm dark:tw-border-slate-800 dark:tw-bg-slate-950 dark:tw-text-slate-50 !tw-border-none tw-p-5 !tw-bg-[#AA8CF9]&quot;]/section[@class=&quot;tw-flex tw-w-full tw-flex-col tw-items-stretch tw-justify-center tw-gap-4 tw-py-4&quot;]/div[@class=&quot;tw-grid tw-items-stretch tw-grid-cols-1 md:tw-grid-cols-2 lg:tw-grid-cols-3 xl:tw-grid-cols-4 tw-mb-[35px] tw-h-full tw-gap-[10px] xl:tw-gap-[16px]&quot;]/article[@class=&quot;tw-flex tw-h-fit tw-w-full tw-flex-col tw-overflow-hidden tw-rounded-[10px] tw-border tw-bg-white&quot;]/div[@class=&quot;tw-flex tw-flex-1 tw-flex-col tw-justify-between tw-gap-[16px] tw-p-[16px]&quot;]/div[@class=&quot;tw-flex tw-flex-wrap tw-gap-[8px] md:tw-flex-nowrap&quot;]/a[@class=&quot;tw-max-w-full tw-w-full tw-transition tw-ease-in-out tw-duration-150 tw-font-bold tw-flex tw-items-center tw-justify-center tw-transition tw-ease-in-out tw-duration-150 styles_buttonVariantOutline__gf_i8 styles_buttonColorBlue__0VHnR tw-rounded-[10px] tw-cursor-pointer tw-text-[14px] tw-py-[5px] tw-px-[10px] !tw-text-center&quot;]</value>
      <webElementGuid>c59e400e-e0e6-4be4-901f-44cd90712df1</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='__next']/div/div[2]/div[2]/div/div/section/div[2]/section/div/article[7]/div/div/a</value>
      <webElementGuid>2d05091c-1e1d-4940-a46a-234d59762a01</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>(//a[contains(text(),'تفاصيل الدورة')])[7]</value>
      <webElementGuid>f1b0515a-32c5-43ed-9d37-145324d9a403</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='مدة الدورة:'])[7]/following::a[1]</value>
      <webElementGuid>38ae4fa4-1244-407f-b23c-45c0f0801cfb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='العلوم - الصف الرابع - فصل اول - رغد فرحانة'])[1]/following::a[1]</value>
      <webElementGuid>ca9c610c-a8ab-4984-9c69-2af16b7339c0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='تفعيل بالبطاقة'])[7]/preceding::a[1]</value>
      <webElementGuid>3d96cf55-3e5c-438b-bebf-370be1647dcd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='سارة خليفه'])[2]/preceding::a[1]</value>
      <webElementGuid>f36fc9d7-60da-4b81-910c-a0a2fb349ec4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>(//a[contains(@href, '/courses/%D8%A7%D9%84%D8%B9%D9%84%D9%88%D9%85-%D8%A7%D9%84%D8%B5%D9%81-%D8%A7%D9%84%D8%B1%D8%A7%D8%A8%D8%B9-%D9%81%D8%B5%D9%84-%D8%A7%D9%88%D9%84-%D8%B1%D8%BA%D8%AF-%D9%81%D8%B1%D8%AD%D8%A7%D9%86%D8%A9')])[2]</value>
      <webElementGuid>e2d91647-dece-4ed9-9f62-a4b22f13ac3d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//article[7]/div/div/a</value>
      <webElementGuid>8bd1565e-8996-400d-b105-b702272f1c98</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = '/courses/%D8%A7%D9%84%D8%B9%D9%84%D9%88%D9%85-%D8%A7%D9%84%D8%B5%D9%81-%D8%A7%D9%84%D8%B1%D8%A7%D8%A8%D8%B9-%D9%81%D8%B5%D9%84-%D8%A7%D9%88%D9%84-%D8%B1%D8%BA%D8%AF-%D9%81%D8%B1%D8%AD%D8%A7%D9%86%D8%A9' and (text() = 'تفاصيل الدورة' or . = 'تفاصيل الدورة')]</value>
      <webElementGuid>bdd45d22-9401-4878-a1cb-723786858e57</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
