<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_for_stop_to_watch</name>
   <tag></tag>
   <elementGuidId>dd576888-f5e7-4232-962c-f9504fba028e</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//button[@type='button']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>button.Button_module_button__779846a6.shared_module_focusable__fd03e359.Button_module_icon__779846a6.exclude-global-button-styles.Tooltip_module_tooltipContainer__d9b61844.PlayButton_module_playButton__78ddc17f.shared_module_focusable__fd03e359</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>04eeca32-d8af-476e-9970-c8c315f614a9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>Button_module_button__779846a6 shared_module_focusable__fd03e359 Button_module_icon__779846a6 exclude-global-button-styles Tooltip_module_tooltipContainer__d9b61844 PlayButton_module_playButton__78ddc17f shared_module_focusable__fd03e359</value>
      <webElementGuid>3fdf516c-a9f2-478e-86f4-8caf5887ad3c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>bcec6d02-a5f9-4158-9437-756026a96e43</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-play-button</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>dd356997-3542-47f9-a354-928b0bf9e52a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-labelledby</name>
      <type>Main</type>
      <value>play-button-tooltip</value>
      <webElementGuid>4cf5a0d2-c810-44a7-b734-728e4c3f17c9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-touch-device</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>b861afc8-86a3-4882-81a2-5d6adcaa5012</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Play</value>
      <webElementGuid>a9c382fe-83b6-4faa-ae1f-5ef43bec674c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;player&quot;)/div[@class=&quot;vp-player-ui-overlays content-area-sibling-enabled&quot;]/div[@class=&quot;ControlBar_module_controlBarWrapper__6e152b0c&quot;]/div[@class=&quot;PlayButton_module_playButtonWrapper__78ddc17f&quot;]/button[@class=&quot;Button_module_button__779846a6 shared_module_focusable__fd03e359 Button_module_icon__779846a6 exclude-global-button-styles Tooltip_module_tooltipContainer__d9b61844 PlayButton_module_playButton__78ddc17f shared_module_focusable__fd03e359&quot;]</value>
      <webElementGuid>f287899f-1146-46c8-8501-ae18367bc07d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/Button_For_Start_TheCourse/Page_- joacademy.com/iframe</value>
      <webElementGuid>5e4fcb26-ce66-42c7-89b7-e54c0c2799e4</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//button[@type='button']</value>
      <webElementGuid>adaf5d8c-d1d6-4b0e-91c5-50f35891df50</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='player']/div[7]/div[8]/div/button</value>
      <webElementGuid>b871edc6-0704-4f46-a4da-5742fbd55fc7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Playing in picture-in-picture'])[1]/following::button[2]</value>
      <webElementGuid>7a96237e-8585-4e29-92e8-31c14c68a4ec</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Quality'])[1]/preceding::button[3]</value>
      <webElementGuid>1424e0a1-97e7-41e4-88b7-dbc1b2fd16d1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Auto'])[1]/preceding::button[3]</value>
      <webElementGuid>3b979486-fec4-46ca-b47f-2fe96e341d5b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/button</value>
      <webElementGuid>16b46287-10a8-4d00-af4d-1e501b7a0943</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@type = 'button' and (text() = 'Play' or . = 'Play')]</value>
      <webElementGuid>e95a085c-d11f-44f6-84f8-77b1596b5f77</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
