<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_for_start_to_watch</name>
   <tag></tag>
   <elementGuidId>9950ed8b-8551-4e0f-b43e-c1f5ec88b8a7</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//button[@data-play-button=&quot;true&quot;]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>path[d=&quot;M19 12C19 12.3557 18.8111 12.6846 18.5039 12.8638L6.50387 19.8638C6.19458 20.0442 5.81243 20.0455 5.50194 19.8671C5.19145 19.6888 5 19.3581 5 19L5 5C5 4.64193 5.19145 4.3112 5.50194 4.13286C5.81243 3.95452 6.19458 3.9558 6.50387 4.13622L18.5039 11.1362C18.8111 11.3154 19 11.6443 19 12Z&quot;]&#xd;
</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>a9faba26-85d1-4137-8862-3291cceb4c42</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>alt</name>
      <type>Main</type>
      <value>طَرْحُ الأعداد الصَّحيحَةِ - حل تمارين ومسائل - 2</value>
      <webElementGuid>3f14da8a-3673-4d58-95a5-4df89e772b4b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>loading</name>
      <type>Main</type>
      <value>lazy</value>
      <webElementGuid>fc857a53-e4a1-436c-a2b9-7c0b2e68db5b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>width</name>
      <type>Main</type>
      <value>200</value>
      <webElementGuid>2c62fe36-c71e-4a58-add7-a584bfd7bd68</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>height</name>
      <type>Main</type>
      <value>112</value>
      <webElementGuid>8e220dc7-d2fa-4bfb-a396-60c5b5581b7d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>decoding</name>
      <type>Main</type>
      <value>async</value>
      <webElementGuid>5fb9d82a-9e79-45ec-8c1e-f8aca50dfc33</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-nimg</name>
      <type>Main</type>
      <value>1</value>
      <webElementGuid>809ca8ad-a156-44ee-8b91-a1fa05f7a150</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>tw-h-[112px] tw-w-full tw-rounded-[14px]</value>
      <webElementGuid>291c0de9-cf42-4cb8-b097-4cc8ee69ec0c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>/_next/static/media/user-courses-intermediate.3bb5fad0.png</value>
      <webElementGuid>6b8e3f00-c537-4a65-a82d-68a1b19e8ef2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;__next&quot;)/div[@class=&quot;tw-flex tw-min-h-screen tw-w-full tw-flex-col tw-justify-between tw-bg-gradient-to-br tw-from-[#905DF5] tw-to-[#813BEC]&quot;]/div[@class=&quot;tw-w-full&quot;]/div[@class=&quot;tw-relative tw-flex tw-w-full&quot;]/div[@class=&quot;tw-flex tw-flex-col tw-relative !tw-w-full tw-px-4 md:tw-px-[30px] lg:tw-px-[40px] 2xl:tw-px-[100px] tw-mx-auto tw-w-full lg:tw-w-[calc(100vw-280px)] !tw-overflow-hidden&quot;]/div[1]/div[@class=&quot;tw-m-auto  tw-py-8&quot;]/section[@class=&quot;tw-mt-10&quot;]/div[@class=&quot;tw-flex tw-flex-col tw-gap-6&quot;]/div[@class=&quot;border-b tw-w-full&quot;]/div[@id=&quot;radix-:r17:&quot;]/div[@class=&quot;tw-pb-4 tw-pt-0 tw-mt-2 tw-hidden tw-flex-wrap tw-justify-center tw-gap-x-8 tw-gap-y-8 !tw-rounded-[10px] tw-bg-[#AA8CF9] !tw-p-6 lg:tw-flex lg:tw-justify-center lg:tw-gap-x-4&quot;]/div[@class=&quot;tw-h-[216px] tw-w-full tw-rounded-[10px] tw-bg-white tw-p-4 sm:tw-w-[232px]&quot;]/div[@class=&quot;tw-relative  tw-cursor-pointer&quot;]/img[@class=&quot;tw-h-[112px] tw-w-full tw-rounded-[14px]&quot;]</value>
      <webElementGuid>93387e64-fbd9-4929-829a-2796ba5695c4</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='radix-:r17:']/div/div/div/img</value>
      <webElementGuid>411523b5-4fa9-41c2-9a82-55694f49a71f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:img</name>
      <type>Main</type>
      <value>//img[@alt='طَرْحُ الأعداد الصَّحيحَةِ - حل تمارين ومسائل - 2']</value>
      <webElementGuid>b8e68b8c-0122-40b2-8d71-a4dce259bd72</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/div/div/img</value>
      <webElementGuid>4eb67569-1803-4691-aeb5-4e4a602dae86</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@alt = 'طَرْحُ الأعداد الصَّحيحَةِ - حل تمارين ومسائل - 2' and @src = '/_next/static/media/user-courses-intermediate.3bb5fad0.png']</value>
      <webElementGuid>9aebc4f1-503f-4004-8f31-c9980104289d</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
