<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_for_stop_to_watch</name>
   <tag></tag>
   <elementGuidId>dd576888-f5e7-4232-962c-f9504fba028e</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div/button</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>button.Button_module_button__779846a6.shared_module_focusable__fd03e359.Button_module_icon__779846a6.exclude-global-button-styles.Tooltip_module_tooltipContainer__d9b61844.PlayButton_module_playButton__78ddc17f.shared_module_focusable__fd03e359</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>0eb344e5-f731-4d49-8a99-f20680260926</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>Button_module_button__779846a6 shared_module_focusable__fd03e359 Button_module_icon__779846a6 exclude-global-button-styles Tooltip_module_tooltipContainer__d9b61844 PlayButton_module_playButton__78ddc17f shared_module_focusable__fd03e359</value>
      <webElementGuid>477f6b5d-0010-4936-b187-0f5f827772b7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>fbb2a78b-456e-489d-bcfd-4c5fcd6fab63</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-play-button</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>c210da9c-69ae-463d-9cc3-8165a80d131e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-labelledby</name>
      <type>Main</type>
      <value>play-button-tooltip</value>
      <webElementGuid>cf5a738e-533d-42e4-a721-3904cff6ae57</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-touch-device</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>f018471e-785e-47d0-b68f-c671d3248302</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Play</value>
      <webElementGuid>c1faf3af-ae4d-460f-973c-be3f9db9d98c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;player&quot;)/div[@class=&quot;vp-player-ui-overlays content-area-sibling-enabled&quot;]/div[@class=&quot;ControlBar_module_controlBarWrapper__6e152b0c&quot;]/div[@class=&quot;PlayButton_module_playButtonWrapper__78ddc17f&quot;]/button[@class=&quot;Button_module_button__779846a6 shared_module_focusable__fd03e359 Button_module_icon__779846a6 exclude-global-button-styles Tooltip_module_tooltipContainer__d9b61844 PlayButton_module_playButton__78ddc17f shared_module_focusable__fd03e359&quot;]</value>
      <webElementGuid>c09223ce-0594-45cb-88a8-c66f488ec34e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/Button_For_Start_TheCourse/Page_- joacademy.com/iframe</value>
      <webElementGuid>1269a35f-15af-446f-b1ad-aa9d94d5207a</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//button[@type='button']</value>
      <webElementGuid>720ec301-b4ac-4aad-94c1-32fe95c38173</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='player']/div[7]/div[8]/div/button</value>
      <webElementGuid>55225da8-5a76-48b7-9c72-11e4f7d40679</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Playing in picture-in-picture'])[1]/following::button[2]</value>
      <webElementGuid>6c8a5f3e-cdcc-48a1-b1cb-0389444e5446</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Quality'])[1]/preceding::button[3]</value>
      <webElementGuid>796cd366-a0a3-47b9-b4b2-9b09ad7581a7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Auto'])[1]/preceding::button[3]</value>
      <webElementGuid>691e7781-4b73-419a-baf1-34156f5cd31c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/button</value>
      <webElementGuid>5dee052e-98f1-46bb-b922-84934a9ac6af</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@type = 'button' and (text() = 'Play' or . = 'Play')]</value>
      <webElementGuid>df6cd2ef-8d4e-4186-b0ee-22474de9ec42</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
