<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Button_for_arrow_Right</name>
   <tag></tag>
   <elementGuidId>c7e99879-9b90-4b61-98e0-a4f719cde3db</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='__next']/div/div[2]/div/div/div/section/div/i</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>i</value>
      <webElementGuid>98d23f2b-e00d-4448-96a0-7be2d9f878f0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ri-arrow-right-s-line  tw-hidden sm:tw-block  tw-cursor-pointer tw-text-5xl tw-text-[#8647EF] hover:tw-scale-125 tw-transition-transform</value>
      <webElementGuid>a57f545d-12da-4ef4-bf36-e5796bff6bb6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;__next&quot;)/div[@class=&quot;tw-flex tw-min-h-screen tw-w-full tw-flex-col tw-justify-between tw-bg-gradient-to-br tw-from-[#905DF5] tw-to-[#813BEC]&quot;]/div[@class=&quot;tw-w-full&quot;]/div[@class=&quot;tw-relative tw-flex tw-w-full&quot;]/div[@class=&quot;tw-flex tw-flex-col tw-relative !tw-w-full tw-w-full !tw-overflow-hidden&quot;]/div[1]/section[@class=&quot;tw-relative tw-m-auto tw-mb-7 tw-w-full tw-max-w-[1168px] tw-rounded-[50px] sm:tw-mt-4 sm:tw-w-[80%] sm:tw-bg-[#AA8CF9] sm:tw-py-8 lg:tw-w-[85%]&quot;]/div[@class=&quot;tw-flex tw-items-center tw-justify-center tw-gap-5 tw-z-1 tw-relative sm:tw-min-h-[480px] sm:tw-px-10&quot;]/i[@class=&quot;ri-arrow-right-s-line  tw-hidden sm:tw-block  tw-cursor-pointer tw-text-5xl tw-text-[#8647EF] hover:tw-scale-125 tw-transition-transform&quot;]</value>
      <webElementGuid>861fdd73-476c-4d18-9e94-40b46fed2acc</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='__next']/div/div[2]/div/div/div/section/div/i</value>
      <webElementGuid>6ad0b1cb-cfd3-4d0c-a50d-b69d7a07a004</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//section/div/i</value>
      <webElementGuid>1c620f2f-b9cc-4f14-baa2-1e3708f31a82</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
