<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>iframe</name>
   <tag></tag>
   <elementGuidId>8c4412f4-0d6d-4c04-9faa-98502068387f</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//iframe[contains(@src, 'vimeo')]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>iframe</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>iframe</value>
      <webElementGuid>1619cf47-98eb-4379-97db-ce4690c242d4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>width</name>
      <type>Main</type>
      <value>640</value>
      <webElementGuid>eaebcb62-95ca-40e4-8159-b0dd0202cf66</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>height</name>
      <type>Main</type>
      <value>360</value>
      <webElementGuid>d91903d4-39a9-40d0-a3e3-79b4ca3351ca</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>https://player.vimeo.com/video/860957620</value>
      <webElementGuid>a818f1a6-c47f-4804-acf4-a1b7499c0f9d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>frameborder</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>009cf11e-9d41-48fc-938b-edadc8e125a6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>allow</name>
      <type>Main</type>
      <value>autoplay; fullscreen; picture-in-picture</value>
      <webElementGuid>cd25cae3-64dc-455d-8881-c17e729d4ab1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;__next&quot;)/div[@class=&quot;tw-flex tw-min-h-screen tw-w-full tw-flex-col tw-justify-between tw-bg-gradient-to-br tw-from-[#905DF5] tw-to-[#813BEC]&quot;]/div[@class=&quot;tw-w-full&quot;]/div[@class=&quot;tw-relative tw-flex tw-w-full&quot;]/div[@class=&quot;tw-flex tw-flex-col tw-relative !tw-w-full tw-w-full !tw-overflow-hidden&quot;]/div[1]/section[@class=&quot;tw-relative tw-m-auto tw-mb-7 tw-w-full tw-max-w-[1168px] tw-rounded-[50px] sm:tw-mt-4 sm:tw-w-[80%] sm:tw-bg-[#AA8CF9] sm:tw-py-8 lg:tw-w-[85%]&quot;]/div[@class=&quot;tw-flex tw-items-center tw-justify-center tw-gap-5 tw-z-1 tw-relative sm:tw-min-h-[480px] sm:tw-px-10&quot;]/div[@class=&quot;tw-w-full&quot;]/div[@class=&quot;[&amp;>iframe]:tw-w-[100%]    tw-h-[250px] tw-w-full sm:tw-h-[400px] [&amp;>iframe]:tw-h-[100%]&quot;]/iframe[1]</value>
      <webElementGuid>8451bcf3-c0d4-406f-ad73-b092ba93d8ea</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='__next']/div/div[2]/div/div/div/section/div/div/div/iframe</value>
      <webElementGuid>566dbeaa-926f-4368-b395-43d091e22f31</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//iframe</value>
      <webElementGuid>7ffedfdf-580e-469c-81bb-14bd9eece46b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//iframe[@src = 'https://player.vimeo.com/video/860957620']</value>
      <webElementGuid>a9642f88-da6a-46ff-ab60-04530b9653a9</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
