<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Close</name>
   <tag></tag>
   <elementGuidId>fee557cf-55cb-4539-a22c-2c9377ddd8be</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>(//button[@type='button'])[8]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>30c968da-8c7b-44fe-a211-8aca55a07e74</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>f3db7b41-350b-40e6-8c2e-5c6190d5b060</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>focus:tw-ring-ring data-[state=open]:tw-bg-accent data-[state=open]:tw-text-muted-foreground tw-absolute tw-end-4 tw-top-4 tw-z-10 tw-m-auto tw-flex tw-h-[35px] tw-h-[45px] tw-w-[35px] tw-w-[45px] tw-cursor-pointer tw-items-center tw-justify-center tw-rounded-full tw-bg-white tw-leading-none tw-shadow tw-transition tw-duration-150 tw-ease-in-out hover:tw-bg-[#efefef] focus:tw-outline-none focus:tw-ring-2 focus:tw-ring-offset-2 disabled:tw-pointer-events-none</value>
      <webElementGuid>27384812-6b89-4018-adf2-ef933e40c128</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Close</value>
      <webElementGuid>6caa5ebf-144f-40e9-9fda-f010174205fd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;radix-:r1a:&quot;)/button[@class=&quot;focus:tw-ring-ring data-[state=open]:tw-bg-accent data-[state=open]:tw-text-muted-foreground tw-absolute tw-end-4 tw-top-4 tw-z-10 tw-m-auto tw-flex tw-h-[35px] tw-h-[45px] tw-w-[35px] tw-w-[45px] tw-cursor-pointer tw-items-center tw-justify-center tw-rounded-full tw-bg-white tw-leading-none tw-shadow tw-transition tw-duration-150 tw-ease-in-out hover:tw-bg-[#efefef] focus:tw-outline-none focus:tw-ring-2 focus:tw-ring-offset-2 disabled:tw-pointer-events-none&quot;]</value>
      <webElementGuid>f2142683-d58e-403b-8966-96ed7531a850</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>(//button[@type='button'])[8]</value>
      <webElementGuid>9991fd34-9c37-4e90-8833-6f4c41bcab14</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='radix-:r1a:']/button</value>
      <webElementGuid>d35fd24e-e641-45f3-bf0b-91325d80c95a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='احصل على العروض'])[1]/following::button[1]</value>
      <webElementGuid>e3e7baed-5bb2-4893-b70b-16318f595402</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='بدأت مفاجآتنا الآن!'])[1]/following::button[2]</value>
      <webElementGuid>c708f732-bb40-4bdf-b4d7-650600518f2c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/button</value>
      <webElementGuid>feca4613-875a-436f-b25c-77ce1e9a79d0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@type = 'button' and (text() = 'Close' or . = 'Close')]</value>
      <webElementGuid>0b150d95-461e-4560-a3aa-02f9dc5ce3d7</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
