<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>editt</name>
   <tag></tag>
   <elementGuidId>64e9c848-bde9-41df-b4b4-163471e1704e</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>[alt='تعديل']</value>
      </entry>
      <entry>
         <key>BASIC</key>
      </entry>
   </selectorCollection>
   <selectorMethod>CSS</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>
