<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_for_stop_to_watch</name>
   <tag></tag>
   <elementGuidId>dd576888-f5e7-4232-962c-f9504fba028e</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>button.Button_module_button__779846a6.shared_module_focusable__fd03e359.Button_module_icon__779846a6.exclude-global-button-styles.Tooltip_module_tooltipContainer__d9b61844.PlayButton_module_playButton__78ddc17f.shared_module_focusable__fd03e359</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//button[@type='button']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>dce8e1d2-4ea6-4a1e-b60b-3e8c900bb7a7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>Button_module_button__779846a6 shared_module_focusable__fd03e359 Button_module_icon__779846a6 exclude-global-button-styles Tooltip_module_tooltipContainer__d9b61844 PlayButton_module_playButton__78ddc17f shared_module_focusable__fd03e359</value>
      <webElementGuid>6457b455-3109-40b3-b6af-9702695f9ee1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>cfee8707-c065-4ee3-8388-58d18d7d4267</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-play-button</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>25417f27-b474-4852-8ac6-056a076f7a8c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-labelledby</name>
      <type>Main</type>
      <value>play-button-tooltip</value>
      <webElementGuid>133d2639-d427-4da4-b7e5-138b818750d7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-touch-device</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>442a08eb-d8de-4e6b-990f-0e883cd4c23b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Play</value>
      <webElementGuid>fcca5655-c6c9-474c-9fc5-a8a7f3837121</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;player&quot;)/div[@class=&quot;vp-player-ui-overlays content-area-sibling-enabled&quot;]/div[@class=&quot;ControlBar_module_controlBarWrapper__6e152b0c&quot;]/div[@class=&quot;PlayButton_module_playButtonWrapper__78ddc17f&quot;]/button[@class=&quot;Button_module_button__779846a6 shared_module_focusable__fd03e359 Button_module_icon__779846a6 exclude-global-button-styles Tooltip_module_tooltipContainer__d9b61844 PlayButton_module_playButton__78ddc17f shared_module_focusable__fd03e359&quot;]</value>
      <webElementGuid>0413a8fd-89d7-4ea4-a15e-8e2188897e38</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/Lenaattoun/Button_For_Start_TheCourse/Page_- joacademy.com/iframe</value>
      <webElementGuid>99ea8e54-153b-4a1a-ac9b-6e79d25fac49</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//button[@type='button']</value>
      <webElementGuid>7a872a01-d6e9-4a8d-8786-2e4b0fb00c9e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='player']/div[7]/div[8]/div/button</value>
      <webElementGuid>126360b3-b4c5-4d32-ae9c-918b0c587198</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Playing in picture-in-picture'])[1]/following::button[2]</value>
      <webElementGuid>6a3806a6-36b5-43fb-aa8d-b4ed01811a36</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Quality'])[1]/preceding::button[3]</value>
      <webElementGuid>1b4c35df-19c8-4134-98e6-68aba3a08bd4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Auto'])[1]/preceding::button[3]</value>
      <webElementGuid>a5c035c0-f2d5-464f-b827-995037e0cd50</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/button</value>
      <webElementGuid>700acd3f-1d48-4e81-a172-ba90bf4bd373</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@type = 'button' and (text() = 'Play' or . = 'Play')]</value>
      <webElementGuid>aa292125-5008-45f0-9833-6c4582de7872</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
