<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Button_For_Back_To_The_Course</name>
   <tag></tag>
   <elementGuidId>b9f9ce6c-08a5-477b-b6ca-0c600899aa35</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='__next']/div/div[2]/div/div/div/div/p</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>p</value>
      <webElementGuid>47c185ee-933a-4d28-b19f-66005c9709c9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value> tw-mt-3 tw-hidden tw-w-fit  tw-cursor-pointer tw-text-xl tw-font-normal tw-text-white tw-underline  tw-underline-offset-8 tw-transition-transform hover:tw-scale-x-105 hover:tw-text-[#AA8CF9]  sm:tw-block</value>
      <webElementGuid>e23f8724-0e24-4403-a40a-d51082948416</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>العودة الى الدورة</value>
      <webElementGuid>434317f1-1c58-4ed0-82ac-8e9ab65f1856</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;__next&quot;)/div[@class=&quot;tw-flex tw-min-h-screen tw-w-full tw-flex-col tw-justify-between tw-bg-gradient-to-br tw-from-[#905DF5] tw-to-[#813BEC]&quot;]/div[@class=&quot;tw-w-full&quot;]/div[@class=&quot;tw-relative tw-flex tw-w-full&quot;]/div[@class=&quot;tw-flex tw-flex-col tw-relative !tw-w-full tw-w-full !tw-overflow-hidden&quot;]/div[1]/div[@class=&quot;tw-m-auto tw-w-full tw-max-w-[1168px] sm:tw-w-[80%] lg:tw-w-[85%]&quot;]/p[@class=&quot;tw-mt-3 tw-hidden tw-w-fit  tw-cursor-pointer tw-text-xl tw-font-normal tw-text-white tw-underline  tw-underline-offset-8 tw-transition-transform hover:tw-scale-x-105 hover:tw-text-[#AA8CF9]  sm:tw-block&quot;]</value>
      <webElementGuid>3ad03d77-3dc6-4cb7-8f5c-ecf0ddae5c7b</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='__next']/div/div[2]/div/div/div/div/p</value>
      <webElementGuid>0c8694db-7890-4694-b805-70cdd67e4afb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='مكتبات'])[1]/following::p[2]</value>
      <webElementGuid>aa8d6dea-8902-4360-892d-08ae6867f586</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='الامتحانات الإلكترونية'])[1]/following::p[2]</value>
      <webElementGuid>dba7dd77-346e-4dcc-bba8-cfd1d05af214</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='الشرح'])[1]/preceding::p[3]</value>
      <webElementGuid>456107ea-057f-4025-bd90-5707aff98634</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='الملخص'])[1]/preceding::p[3]</value>
      <webElementGuid>a86850cc-9958-4b40-b2a5-2255c02d357d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='العودة الى الدورة']/parent::*</value>
      <webElementGuid>0da03058-4f6a-40a3-a803-16d7ae31e211</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/p</value>
      <webElementGuid>981aea53-c8db-405d-9570-7ec0e7f50856</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//p[(text() = 'العودة الى الدورة' or . = 'العودة الى الدورة')]</value>
      <webElementGuid>0217f9d5-2d1a-4774-90cc-87b1652ba183</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
