<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Button_for_arrow_left</name>
   <tag></tag>
   <elementGuidId>e7eed252-5c49-4cd4-8372-f50c21f4f919</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='__next']/div/div[2]/div/div/div/section/div/i[2]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>i</value>
      <webElementGuid>c311c433-7599-4bb9-af7c-1b56afac3d39</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ri-arrow-left-s-line  tw-hidden sm:tw-block  tw-cursor-pointer tw-text-5xl tw-text-[#8647EF] hover:tw-scale-125 tw-transition-transform</value>
      <webElementGuid>23828e84-c37f-4886-aa84-8c89843ad4aa</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;__next&quot;)/div[@class=&quot;tw-flex tw-min-h-screen tw-w-full tw-flex-col tw-justify-between tw-bg-gradient-to-br tw-from-[#905DF5] tw-to-[#813BEC]&quot;]/div[@class=&quot;tw-w-full&quot;]/div[@class=&quot;tw-relative tw-flex tw-w-full&quot;]/div[@class=&quot;tw-flex tw-flex-col tw-relative !tw-w-full tw-w-full !tw-overflow-hidden&quot;]/div[1]/section[@class=&quot;tw-relative tw-m-auto tw-mb-7 tw-w-full tw-max-w-[1168px] tw-rounded-[50px] sm:tw-mt-4 sm:tw-w-[80%] sm:tw-bg-[#AA8CF9] sm:tw-py-8 lg:tw-w-[85%]&quot;]/div[@class=&quot;tw-flex tw-items-center tw-justify-center tw-gap-5 tw-z-1 tw-relative sm:tw-min-h-[480px] sm:tw-px-10&quot;]/i[@class=&quot;ri-arrow-left-s-line  tw-hidden sm:tw-block  tw-cursor-pointer tw-text-5xl tw-text-[#8647EF] hover:tw-scale-125 tw-transition-transform&quot;]</value>
      <webElementGuid>a7cfa3be-d7ea-423f-9d9b-6348cf4dea71</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='__next']/div/div[2]/div/div/div/section/div/i[2]</value>
      <webElementGuid>e227aed6-f3a9-49d9-a1da-1db35dd8ac67</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//i[2]</value>
      <webElementGuid>f4e8de40-9cc0-4a26-a67a-b39c45cc02f1</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
