<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Enter_to_TheLesson</name>
   <tag></tag>
   <elementGuidId>6ddefc92-bbf3-4ac8-a54f-2362a5fd0a9c</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>i.ri-play-circle-line:nth-of-type(1)</value>
      </entry>
      <entry>
         <key>XPATH</key>
      </entry>
   </selectorCollection>
   <selectorMethod>CSS</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>path</value>
      <webElementGuid>01903e53-1de3-4c48-815b-bddc76bb7646</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>d</name>
      <type>Main</type>
      <value>m6 9 6 6 6-6</value>
      <webElementGuid>0b8ee7f9-55db-4005-8e85-4aca27cab321</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;radix-:r16:&quot;)/svg[@class=&quot;lucide lucide-chevron-down tw-h-6  tw-w-6 tw-shrink-0 tw-transition-transform tw-duration-200&quot;]/path[1]</value>
      <webElementGuid>17b70b9b-e7cc-4438-a492-761b58f73803</webElementGuid>
   </webElementProperties>
</WebElementEntity>
