<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_for_courses_favoretpage</name>
   <tag></tag>
   <elementGuidId>c2b610b5-4593-4fe3-96f8-98fb5a602844</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//p[(text() = 'دورات' or . = 'دورات')]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>p</value>
      <webElementGuid>bd309161-f0f2-4f68-a5c5-93fd5854a90e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>tw-whitespace-nowrap tw-text-center tw-text-[16px] tw-font-normal tw-text-[#0D2755]</value>
      <webElementGuid>3a38f9cd-f711-4d52-8311-22463f8320b9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>دورات</value>
      <webElementGuid>6975d9cc-f977-40bd-95ea-7febac28ec44</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;__next&quot;)/div[@class=&quot;tw-flex tw-min-h-screen tw-w-full tw-flex-col tw-justify-between tw-bg-gradient-to-br tw-from-[#905DF5] tw-to-[#813BEC]&quot;]/div[@class=&quot;tw-w-full&quot;]/div[@class=&quot;tw-relative tw-flex tw-w-full&quot;]/div[@class=&quot;tw-flex tw-flex-col tw-relative !tw-w-full tw-px-4 md:tw-px-[30px] lg:tw-px-[40px] 2xl:tw-px-[100px] tw-mx-auto tw-w-full lg:tw-w-[calc(100vw-280px)] !tw-overflow-hidden&quot;]/div[1]/main[@class=&quot;tw-mt-4 tw-pb-[20px] sm:tw-pb-[50px]&quot;]/section[@class=&quot;tw-mb-[10px] tw-flex tw-flex-wrap tw-items-center tw-gap-[10px]&quot;]/button[@class=&quot;tw-flex tw-h-[45px] tw-items-center tw-justify-center tw-gap-[10px] tw-rounded-[14px] tw-px-[20px] tw-py-[10px] tw-font-semibold tw-shadow tw-transition tw-duration-150 tw-ease-in-out hover:tw-bg-[#efefef] tw-bg-white&quot;]/p[@class=&quot;tw-whitespace-nowrap tw-text-center tw-text-[16px] tw-font-normal tw-text-[#0D2755]&quot;]</value>
      <webElementGuid>efcf0f6f-ecb4-48f4-93af-0b11d843ebf8</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='__next']/div/div[2]/div[2]/div[2]/div/main/section/button[2]/p</value>
      <webElementGuid>c9bdc85b-e957-41d8-83c8-ec10aaec6dbe</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='مفضلتي'])[2]/following::p[3]</value>
      <webElementGuid>79cbf906-e913-4cea-8af0-f9b4166e70d6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='المدرسة'])[1]/following::p[3]</value>
      <webElementGuid>c44e1fa3-9a96-4304-b061-33dbb35253c7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='شرح و ورقة عمل Unit5 The dolphins are jumping لمادة اللغة الانجليزية الصف الرابع ف1'])[1]/preceding::p[2]</value>
      <webElementGuid>f8f8dc6a-d02a-4eaf-aee7-41358d642142</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='اللغة الانجليزية (منهاج حكومي) الصف الرابع - فصل أول'])[1]/preceding::p[2]</value>
      <webElementGuid>c0348bd0-2385-45ea-86d9-a790e4e69b0b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//button[2]/p</value>
      <webElementGuid>3f229226-fab8-4b34-8a3e-9f656d7668f8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//p[(text() = 'دورات' or . = 'دورات')]</value>
      <webElementGuid>d0a88d2e-f559-48a8-b9b1-5cafd3fdc24f</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
