<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_for_download_TheFile_favoretpage</name>
   <tag></tag>
   <elementGuidId>36802aff-0a99-45a1-a8c0-9cf5022762a9</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>div.tw-flex.tw-items-center.tw-justify-center.tw-gap-2.tw-whitespace-nowrap.tw-text-white</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='__next']/div/div[2]/div[2]/div[2]/div/main/section[2]/div/div/article/section/div/button[2]/div</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>74f49da8-732d-4eaf-beed-cc40be194051</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>tw-flex tw-items-center tw-justify-center tw-gap-2 tw-whitespace-nowrap tw-text-white</value>
      <webElementGuid>b73779c9-6643-4dee-9e00-e80edbb660f0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>تحميل الملف</value>
      <webElementGuid>60591ea4-47ae-4cae-9094-1ac5e76af4b1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;__next&quot;)/div[@class=&quot;tw-flex tw-min-h-screen tw-w-full tw-flex-col tw-justify-between tw-bg-gradient-to-br tw-from-[#905DF5] tw-to-[#813BEC]&quot;]/div[@class=&quot;tw-w-full&quot;]/div[@class=&quot;tw-relative tw-flex tw-w-full&quot;]/div[@class=&quot;tw-flex tw-flex-col tw-relative !tw-w-full tw-px-4 md:tw-px-[30px] lg:tw-px-[40px] 2xl:tw-px-[100px] tw-mx-auto tw-w-full lg:tw-w-[calc(100vw-280px)] !tw-overflow-hidden&quot;]/div[1]/main[@class=&quot;tw-mt-4 tw-pb-[20px] sm:tw-pb-[50px]&quot;]/section[@class=&quot;tw-py-4&quot;]/div[@class=&quot;tw-flex tw-flex-col tw-items-center tw-justify-center tw-mb-[35px] tw-h-full tw-gap-[10px] xl:tw-gap-[16px]&quot;]/div[@class=&quot;tw-relative tw-w-full&quot;]/article[@class=&quot;tw-flex tw-w-full tw-cursor-pointer tw-overflow-hidden tw-rounded-[10px] tw-border tw-gap-4 tw-p-4 tw-bg-[#F9F9F9]&quot;]/section[@class=&quot;tw-flex tw-flex-1 tw-grow tw-items-start tw-justify-between&quot;]/div[@class=&quot;tw-flex tw-h-full tw-items-end tw-gap-3&quot;]/button[@class=&quot;tw-inline-flex tw-items-center tw-justify-center tw-whitespace-nowrap tw-rounded-md tw-text-sm tw-font-medium tw-ring-offset-white tw-transition-colors focus-visible:tw-outline-none focus-visible:tw-ring-2 focus-visible:tw-ring-slate-950 focus-visible:tw-ring-offset-2 disabled:tw-pointer-events-none disabled:tw-opacity-50 dark:tw-ring-offset-slate-950 dark:focus-visible:tw-ring-slate-300 hover:tw-bg-slate-100 hover:tw-text-slate-900 dark:hover:tw-bg-slate-800 dark:hover:tw-text-slate-50 tw-h-10 tw-px-4 tw-py-2 lg:tw-w-[151px] tw-w-full !tw-rounded-[14px] tw-bg-[#F8F6F6] hover:tw-bg-[#F1F1F1] !tw-bg-[#1A428A] !tw-rounded-[8px] !tw-w-full medium&quot;]/div[@class=&quot;tw-flex tw-items-center tw-justify-center tw-gap-2 tw-whitespace-nowrap tw-text-white&quot;]</value>
      <webElementGuid>d12f24d0-3447-4bbd-b6eb-366039b8f194</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='__next']/div/div[2]/div[2]/div[2]/div/main/section[2]/div/div/article/section/div/button[2]/div</value>
      <webElementGuid>983303a3-5eee-4b74-8030-66514692d371</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='المشاركة'])[1]/following::div[1]</value>
      <webElementGuid>0678f82d-579c-47c4-95ef-7e4bf7c080c5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='| عدد مرات التحميل (2)'])[1]/following::div[4]</value>
      <webElementGuid>4eb9273b-e359-402b-9e8d-b0a02fbd77c4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='اللغة الانجليزية (منهاج حكومي) الصف الرابع - فصل أول'])[2]/preceding::div[2]</value>
      <webElementGuid>e2324019-e051-4c8f-be09-6cc525e094b4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='معلم جو أكاديمي صفوف'])[2]/preceding::div[2]</value>
      <webElementGuid>31db2921-a02b-4844-a7cf-208194b9ba4a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='تحميل الملف']/parent::*</value>
      <webElementGuid>6756577a-119e-4665-8ddf-00fb6e5a6599</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//button[2]/div</value>
      <webElementGuid>c8a8e8f7-d61d-414c-a144-54a6a169ff21</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = 'تحميل الملف' or . = 'تحميل الملف')]</value>
      <webElementGuid>be1c28bb-6584-45ba-84d0-123b8c62c425</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
