<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_for_files_favoretpage</name>
   <tag></tag>
   <elementGuidId>5550f10f-dbd6-4d4f-94db-8d16e1efda3f</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//p[(text() = 'معلمون' or . = 'معلمون')]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>p</value>
      <webElementGuid>d72b3def-cdc2-498b-994a-fffad590ad7e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>tw-whitespace-nowrap tw-text-center tw-text-[16px] tw-font-normal tw-text-[#0D2755]</value>
      <webElementGuid>fc3bcd94-1cee-4cc2-a9e8-b2993329558b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>معلمون</value>
      <webElementGuid>4fe1526c-187a-4cb7-ae70-3d1095b60d42</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;__next&quot;)/div[@class=&quot;tw-flex tw-min-h-screen tw-w-full tw-flex-col tw-justify-between tw-bg-gradient-to-br tw-from-[#905DF5] tw-to-[#813BEC]&quot;]/div[@class=&quot;tw-w-full&quot;]/div[@class=&quot;tw-relative tw-flex tw-w-full&quot;]/div[@class=&quot;tw-flex tw-flex-col tw-relative !tw-w-full tw-px-4 md:tw-px-[30px] lg:tw-px-[40px] 2xl:tw-px-[100px] tw-mx-auto tw-w-full lg:tw-w-[calc(100vw-280px)] !tw-overflow-hidden&quot;]/div[1]/main[@class=&quot;tw-mt-4 tw-pb-[20px] sm:tw-pb-[50px]&quot;]/section[@class=&quot;tw-mb-[10px] tw-flex tw-flex-wrap tw-items-center tw-gap-[10px]&quot;]/button[@class=&quot;tw-flex tw-h-[45px] tw-items-center tw-justify-center tw-gap-[10px] tw-rounded-[14px] tw-px-[20px] tw-py-[10px] tw-font-semibold tw-shadow tw-transition tw-duration-150 tw-ease-in-out hover:tw-bg-[#efefef] tw-bg-white&quot;]/p[@class=&quot;tw-whitespace-nowrap tw-text-center tw-text-[16px] tw-font-normal tw-text-[#0D2755]&quot;]</value>
      <webElementGuid>f985faab-3927-4dcc-bdf2-0dfc46679000</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='__next']/div/div[2]/div[2]/div[2]/div/main/section/button[3]/p</value>
      <webElementGuid>2c490fb8-e955-40bd-b64e-32070d146d60</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='مفضلتي'])[2]/following::p[4]</value>
      <webElementGuid>f060b0bd-2ef9-4e38-a044-84598d350f24</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='المدرسة'])[1]/following::p[4]</value>
      <webElementGuid>e9d14337-abe5-4aa5-83ad-24ea6120e8cd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='تذييل جو أكاديمي'])[1]/preceding::p[7]</value>
      <webElementGuid>4d274a2a-e120-4c12-b6ce-9e08ff5d9897</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='روابط سريعة'])[1]/preceding::p[7]</value>
      <webElementGuid>7d4ac52c-e7f7-40df-b30f-f5a2a04dda86</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//button[3]/p</value>
      <webElementGuid>cfd57a6f-fc6f-46e6-b959-dbac183bbe74</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//p[(text() = 'معلمون' or . = 'معلمون')]</value>
      <webElementGuid>5a901390-4253-4349-acc8-c1bb2eaccded</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
